version: '3.4'

services:
  app:
    build:
      target: dev
    image: libero/article-page:${IMAGE_TAG:-master}-dev
    volumes:
      - ../jest.config.js:/app/jest.config.js
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../src/:/app/src
      - ../stryker.conf.js:/app/stryker.conf.js
      - ../test/:/app/test
      - ../tsconfig.json:/app/tsconfig.json
